services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PORT_WEB_CONSOLE: ${MINIO_PORT_WEB_CONSOLE}
      MINIO_PORT_S3_API: ${MINIO_PORT_S3_API}
    ports:
      - "${MINIO_PORT_S3_API}:${MINIO_PORT_S3_API}"
      - "${MINIO_PORT_WEB_CONSOLE}:${MINIO_PORT_WEB_CONSOLE}"
    command: server /data --console-address ":${MINIO_PORT_WEB_CONSOLE}"
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data: